create extension if not exists pgcrypto;

create table if not exists public.product_candidates (
    id uuid primary key default gen_random_uuid(),
    source_platform text not null default 'ozon',
    source_product_id text not null unique,
    title text,
    detail_title text,
    source_url text,
    image_url text,
    image_path text,
    detail_image_url text,
    price numeric,
    detail_price numeric,
    category text,
    brand text,
    attributes jsonb not null default '[]'::jsonb,
    monthly_sales numeric,
    daily_sales numeric,
    growth_rate numeric,
    return_rate numeric,
    conversion_rate numeric,
    ctr numeric,
    cart_add_rate numeric,
    search_views numeric,
    ad_share numeric,
    promotion_days numeric,
    weight_grams numeric,
    shipping_mode text,
    sellers numeric,
    lowest_competitor text,
    listed_days numeric,
    avg_price numeric,
    score integer,
    passed boolean not null default true,
    warnings jsonb not null default '[]'::jsonb,
    fail_reasons jsonb not null default '[]'::jsonb,
    raw_payload jsonb not null default '{}'::jsonb,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

create table if not exists public.supplier_links (
    id uuid primary key default gen_random_uuid(),
    source_platform text not null default 'ozon',
    source_product_id text not null,
    source_title text,
    source_product_url text,
    source_image_url text,
    source_image_path text,
    source_price numeric,
    supplier_platform text not null default '1688',
    supplier_title text,
    supplier_product_url text not null,
    supplier_image_url text,
    supplier_price numeric,
    supplier_price_text text,
    supplier_unit_price numeric,
    supplier_unit_price_text text,
    supplier_weight_text text,
    supplier_weight_grams numeric,
    supplier_attributes jsonb not null default '[]'::jsonb,
    supplier_seller text,
    ai_image_same_product boolean,
    ai_image_match_score integer,
    ai_image_confidence text,
    ai_image_summary text,
    ai_same_product boolean,
    ai_parameter_gap text,
    ai_match_score integer,
    ai_confidence text,
    ai_summary text,
    ai_difference_points jsonb not null default '[]'::jsonb,
    search_method text,
    raw_payload jsonb not null default '{}'::jsonb,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    unique (source_product_id, supplier_product_url)
);
